# Change these first
owner: bklo94 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: qBittorrent
    url: $QBITTORRENT_URL
  - name: VNStat
    url: $VNSTAT_URL
  - name: Portainer
    url: $PORTAINER_URL
  - name: Plex
    url: $PLEX_URL

status-website:
  theme: night
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Brandon's Homelab Status Page**"
  introMessage: Powered by GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
